Fix poor logic

diff --git a/mpv-get-property b/mpv-get-property
--- a/mpv-get-property
+++ b/mpv-get-property
@@ -4,30 +4,26 @@
 # Second argument: mpv property to get from the socket
 
 SOCKET="${1:?Must provide socket as first argument}"
-if [[ -e "${SOCKET}" ]]; then
-  if [[ ! -S "${SOCKET}" ]]; then
-    echo "Path is not a socket: ${SOCKET}" >&2
-    exit 2
-  fi
-else
-  echo "Path doesn't exist: ${SOCKET}" >&2
+abort() {
+  echo "$1" >&2
   exit 2
-fi
+}
+
+[[ ! -e "$SOCKET" ]] && abort "Path doesn't exist: $SOCKET"
+[[ ! -S "$SOCKET" ]] && abort "Path is not a socket: $SOCKET"
+
 PROPERTY="${2:?Must provide property as second argument}"
 readonly SOCKET PROPERTY
 
 # interpolate the property and capture the response
-MPV_RESP="$(printf '{ "command": ["get_property", "%s" ] }\n' "${PROPERTY}" | socat - "${SOCKET}")"
+MPV_RESP="$(printf '{ "command": ["get_property", "%s" ] }\n' "$PROPERTY" | socat - "$SOCKET")"
 
 # to reduce overhead from multiple jq calls -- try the common case first
 # select (filter) and extract data if it succeeded
 DATA="$(jq -r 'select(.error == "success") | .data' <<<"$MPV_RESP")"
-if [[ -z "$DATA" ]]; then
-  # was empty, so extract/dump error
-  err="$(echo "${MPV_RESP}" | jq -r '.error')"
-  echo -e "Error: ${err}\nResponse:" >&2
-  jq <<<"${MPV_RESP}" >&2
-  exit 1
-fi
-# data wasn't empty; succeeded
-echo "${DATA}"
+[[ -n "$DATA" ]] && { echo "$DATA" ; exit 0; }
+# was empty, so extract/dump error
+err="$(echo "${MPV_RESP}" | jq -r '.error')"
+echo -e "Error: $err\nResponse:" >&2
+jq <<<"$MPV_RESP" >&2
+exit 1
